name: Build wheels

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest] # windows-latest

    steps:
      # Check out repository using git-lfs
      - uses: actions/checkout@v3
        with:
          lfs: true

      # Install Python used to run cibuildwheel
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Fetch BÍN source data from Árnastofnun
      - name: Fetch BÍN source data and build compressed.bin
        run: |
          pip3 install -e .
          echo "Fetching BÍN source data..."
          cd src/islenska/resources
          wget --quiet -O KRISTINsnid.csv.zip https://bin.arnastofnun.is/django/api/nidurhal/?file=KRISTINsnid.csv.zip
          unzip -q KRISTINsnid.csv.zip
          rm KRISTINsnid.csv.*
          cd ../../..
          echo "Building compressed.bin..."
          python3 tools/binpack.py
          python3 tools/dawgbuilder.py

      - name: Install cibuildwheel
        run: python -m pip install --upgrade wheel setuptools pip cibuildwheel==2.11.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # Options (https://cibuildwheel.readthedocs.io/en/stable/options/)
        env:
          CIBW_SKIP: cp36-* cp311-* *musllinux*
          CIBW_BEFORE_BUILD_MACOS: python3 -m pip install --upgrade setuptools wheel cffi
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BUILD_FRONTEND: "build"
          # CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
